apiVersion: v1
kind: Namespace
metadata:
  name: bd-demo
  labels:
    environment: live-demo
    istio-injection: enabled
    LoB: "Central-IT"
    ns-owner: "John_Farnham"
    tool-owner: "tekton_retail"
